-- Create products table

DROP TABLE IF EXISTS products.t_product;

CREATE TABLE products.t_product (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(100),
	category VARCHAR(50),
	description TEXT,
	price DECIMAL(12,2),
	product_code VARCHAR(20) UNIQUE NOT NULL,
	created_at TIMESTAMP
);
