-- Create products table

DROP TABLE IF EXISTS products.t_product;

CREATE TABLE products.t_product (
	ProductId INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR(100),
	Category VARCHAR(50),
	Description TEXT,
	Price DECIMAL(12,2),
	ProductCode VARCHAR(20),
	CreatedAt TIMESTAMP
);
