version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: AgoraDB
    ports:
      - "5432:5432"
    volumes:
      - agora-postgres-data:/var/lib/postgresql/data
    networks:
      - agora-dev-net

volumes:
  agora-postgres-data:

networks:
  agora-dev-net: