global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'catalog-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'cart-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8082']
