FROM golang:1.24 AS builder
WORKDIR /app/internal/services/notification

# Build dependencies
COPY internal/services/notification/go.mod internal/services/notification/go.sum .
COPY internal/pkg/go.mod internal/pkg/go.sum ../../pkg
RUN go mod download

# Build the application
COPY internal/services/notification .
COPY internal/pkg ../../pkg

WORKDIR /app/internal/services/notification
RUN go build -o notification-service ./cmd/main.go
CMD ["./notification-service"]