FROM golang:1.24 AS builder
WORKDIR /app/internal/services/cart

# Build dependencies
COPY internal/services/cart/go.mod internal/services/cart/go.sum .
COPY internal/pkg/go.mod internal/pkg/go.sum ../../pkg
RUN go mod download

# Build the application
COPY internal/services/cart .
COPY internal/pkg ../../pkg

WORKDIR /app/internal/services/cart
RUN go build -o cart-service ./cmd/main.go
CMD ["./cart-service"]