FROM golang:1.24 AS builder
WORKDIR /app/internal/services/catalog

# Build dependencies
COPY internal/services/catalog/go.mod internal/services/catalog/go.sum .
COPY internal/pkg/go.mod internal/pkg/go.sum ../../pkg
RUN go mod download

# Build the application
COPY internal/services/catalog .
COPY internal/pkg ../../pkg

WORKDIR /app/internal/services/catalog
RUN go build -o catalog-service ./cmd/main.go
CMD ["./catalog-service"]